name: Rerun Failed Job Once

on:
  workflow_run:
    workflows: ["CISA KEV"]
    types:
      - completed

jobs:
  rerun:
    runs-on: ubuntu-latest
    env:
      RERUN_ATTEMPT: 0

    steps:
      - name: Check previous job outcome
        id: check_job
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const outcome = context.payload.workflow_run.jobs['rerun'].conclusion;
            return outcome === 'failure';

      - name: Rerun job
        if: steps.check_job.outputs.rerun == 'true' && env.RERUN_ATTEMPT == '0'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: workflow } = await octokit.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id
            });

            await octokit.actions.reRunWorkflow({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: workflow.id
            });

      - name: Update RERUN_ATTEMPT
        if: steps.check_job.outputs.rerun == 'true' && env.RERUN_ATTEMPT == '0'
        run: echo "RERUN_ATTEMPT=1" >> $GITHUB_ENV
